apiVersion: v1
kind: Secret
metadata:
  name: azure-vault-secret
  labels:
    secrets-store.csi.k8s.io/used: "true"
data:
    clientid: NTQwODNkMDItOTFhYy00MTkwLWFhNWUtYTU3YTU4NmUyYjQy
    clientsecret: NUVLOFF+SUZBX0suV0RhcGl5SGNoNlZBeHRxb1V5UUt3TlEua2MxVQ==
