apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-vault-secret-provider
spec:
  provider: azure
  secretObjects:
    - data:
        - key: PARAMETROS_DATABASE_USERNAME 
          objectName: PARAMETROS-DATABASE-USERNAME
      secretName: azure-vault-secret-plain
      type: Opaque     
  parameters:
     keyvaultName: vault-josemi
     tenantId: 8810e754-8fb5-45bd-9d92-bb64623c49f4
     objects: |
       array:
        - |
          objectName: PARAMETROS-DATABASE-USERNAME
          objectType: secret
        - |
          objectName: PARAMETROS-DATABASE-PASSWORD
          objectType: secret
    